server:
  port : 8080
spring:
  temporal:
    connection:
      target: local
    # namespace: <> # https://docs.temporal.io/cloud/#temporal-cloud-namespace-id
    # connection:
    #   target: <>.tmprl.cloud:7233
    #   mtls:
    #     key-file: <>.key
    #     cert-chain-file: <>.pem
    workers-auto-discovery:
      packages: com.brendan.temporal
greeting: Hello